name: PR Playground Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  playground-preview:
    name: Update Playground Preview
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ./.github/workflows/playground-preview.yml
    with:
      preview-mode: "description"
      plugin-path: .
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
